export const studentData = [
  {
    id: 1 * Math.random(),
    fullName: "Otajonov Abdurahmon",
    phoneNumber: "123-45-67-1",
    status: "UNM",
    delete: null,
  },
  {
    id: 2 * Math.random(),
    fullName: "Xusanov Shoaziz",
    phoneNumber: "123-45-67-2",
    status: "ST",
  },
  {
    id: 3 * Math.random(),
    fullName: "Saidnazarova Odina",
    phoneNumber: "123-45-67-3",
    status: "ST",
  },
  {
    id: 4 * Math.random(),
    fullName: "Murodillayev Hojiakbar",
    phoneNumber: "123-45-67-4",
    status: "BS",
  },
  {
    id: 5 * Math.random(),
    fullName: "Zohidova Ruqiya",
    phoneNumber: "123-45-67-5",
    status: "ST",
  },
  {
    id: 6 * Math.random(),
    fullName: "Mahsutaliyev Abdulaziz",
    phoneNumber: "123-45-67-6",
    status: "BS",
  },
  {
    id: 7 * Math.random(),
    fullName: "Tohirov Azizbek",
    phoneNumber: "123-45-67-7",
    status: "UNM",
  },
  {
    id: 8 * Math.random(),
    fullName: "Fayzullayev Sobirjon",
    phoneNumber: "123-45-67-8",
    status: "BS",
  },
  {
    id: 9 * Math.random(),
    fullName: "Nizamov Sardor",
    phoneNumber: "123-45-67-9",
    status: "ST",
  },
  {
    id: 10 * Math.random(),
    fullName: "G'ofurov Sayfiddin",
    phoneNumber: "123-45-67-10",
    status: "UNM",
  },
  {
    id: 11 * Math.random(),
    fullName: "Ibrohim Uraimov",
    phoneNumber: "123-45-67-11",
    status: "UNM",
  },
  {
    id: 12 * Math.random(),
    fullName: "Kamoliddin Islamov",
    phoneNumber: "123-45-67-12",
    status: "ST",
  },
  {
    id: 13 * Math.random(),
    fullName: "Hamidov Azimxon",
    phoneNumber: "123-45-67-13",
    status: "BS",
  },
  {
    id: 1 * Math.random(),
    fullName: "Otajonov Abdurahmon",
    phoneNumber: "123-45-67-1",
    status: "UNM",
  },
  {
    id: 2 * Math.random(),
    fullName: "Xusanov Shoaziz",
    phoneNumber: "123-45-67-2",
    status: "ST",
  },
  {
    id: 3 * Math.random(),
    fullName: "Saidnazarova Odina",
    phoneNumber: "123-45-67-3",
    status: "ST",
  },
  {
    id: 4 * Math.random(),
    fullName: "Murodillayev Hojiakbar",
    phoneNumber: "123-45-67-4",
    status: "BS",
  },
  {
    id: 5 * Math.random(),
    fullName: "Zohidova Ruqiya",
    phoneNumber: "123-45-67-5",
    status: "ST",
  },
  {
    id: 6 * Math.random(),
    fullName: "Mahsutaliyev Abdulaziz",
    phoneNumber: "123-45-67-6",
    status: "BS",
  },
  {
    id: 7 * Math.random(),
    fullName: "Tohirov Azizbek",
    phoneNumber: "123-45-67-7",
    status: "UNM",
  },
  {
    id: 8 * Math.random(),
    fullName: "Fayzullayev Sobirjon",
    phoneNumber: "123-45-67-8",
    status: "BS",
  },
  {
    id: 9 * Math.random(),
    fullName: "Nizamov Sardor",
    phoneNumber: "123-45-67-9",
    status: "ST",
  },
  {
    id: 10 * Math.random(),
    fullName: "G'ofurov Sayfiddin",
    phoneNumber: "123-45-67-10",
    status: "UNM",
  },
  {
    id: 11 * Math.random(),
    fullName: "Ibrohim Uraimov",
    phoneNumber: "123-45-67-11",
    status: "UNM",
  },
  {
    id: 12 * Math.random(),
    fullName: "Kamoliddin Islamov",
    phoneNumber: "123-45-67-12",
    status: "ST",
  },
  {
    id: 13 * Math.random(),
    fullName: "Hamidov Azimxon",
    phoneNumber: "123-45-67-13",
    status: "BS",
  },
  {
    id: 1 * Math.random(),
    fullName: "Otajonov Abdurahmon",
    phoneNumber: "123-45-67-1",
    status: "UNM",
  },
  {
    id: 2 * Math.random(),
    fullName: "Xusanov Shoaziz",
    phoneNumber: "123-45-67-2",
    status: "ST",
  },
  {
    id: 3 * Math.random(),
    fullName: "Saidnazarova Odina",
    phoneNumber: "123-45-67-3",
    status: "ST",
  },
  {
    id: 4 * Math.random(),
    fullName: "Murodillayev Hojiakbar",
    phoneNumber: "123-45-67-4",
    status: "BS",
  },
  {
    id: 5 * Math.random(),
    fullName: "Zohidova Ruqiya",
    phoneNumber: "123-45-67-5",
    status: "ST",
  },
  {
    id: 6 * Math.random(),
    fullName: "Mahsutaliyev Abdulaziz",
    phoneNumber: "123-45-67-6",
    status: "BS",
  },
  {
    id: 7 * Math.random(),
    fullName: "Tohirov Azizbek",
    phoneNumber: "123-45-67-7",
    status: "UNM",
  },
  {
    id: 8 * Math.random(),
    fullName: "Fayzullayev Sobirjon",
    phoneNumber: "123-45-67-8",
    status: "BS",
  },
  {
    id: 9 * Math.random(),
    fullName: "Nizamov Sardor",
    phoneNumber: "123-45-67-9",
    status: "ST",
  },
  {
    id: 10 * Math.random(),
    fullName: "G'ofurov Sayfiddin",
    phoneNumber: "123-45-67-10",
    status: "UNM",
  },
  {
    id: 11 * Math.random(),
    fullName: "Ibrohim Uraimov",
    phoneNumber: "123-45-67-11",
    status: "UNM",
  },
  {
    id: 12 * Math.random(),
    fullName: "Kamoliddin Islamov",
    phoneNumber: "123-45-67-12",
    status: "ST",
  },
  {
    id: 13 * Math.random(),
    fullName: "Hamidov Azimxon",
    phoneNumber: "123-45-67-13",
    status: "BS",
  },
];
